import Header from "../components/Header";

export default function OfferPage() {
  return (
    <main className="flex flex-1 flex-col  bg-white overflow-auto">
      <Header />

      <div className="flex flex-col flex-1  overflow-hidden">
        <div className="flex-1 flex flex-col overflow-y-auto  scrollbar-hide">
          <div className="max-w-4xl mx-auto py-12 px-4">
            <h1 className="text-3xl font-bold mb-8 text-center">
              Public Offer
            </h1>

            <div className="prose prose-lg max-w-none">
              <h2>1. General Provisions</h2>
              <p>
                This document is a public offer (proposal) of AxonDigital
                (hereinafter referred to as the &quot;Provider&quot;) for the
                provision of information services on the website.
              </p>

              <h2>2. Subject of the Offer</h2>
              <p>
                The Provider grants the User access to information materials and
                services available on the website, including AI assistant for
                collecting information and creating briefs.
              </p>

              <h2>3. Limitation of Liability</h2>
              <p>
                All information provided on the website, including information
                generated by the AI assistant, is for informational purposes
                only. The Provider assumes no responsibility for decisions made
                by the User based on the information received.
              </p>

              <h2>4. Use of AI Assistant</h2>
              <p>
                The AI assistant is designed to help create briefs and collect
                information. Responses generated by the AI assistant are
                automatically formed based on data provided by the User and do
                not constitute professional advice.
              </p>

              <h2>5. Confidentiality</h2>
              <p>
                The Provider undertakes not to disclose information received
                from the User, except in cases provided for by law. However, the
                Provider cannot guarantee complete security of data transmission
                over the Internet.
              </p>

              <h2>6. Final Provisions</h2>
              <p>
                This offer is valid indefinitely. The Provider reserves the
                right to make changes to the terms of the offer at any time
                without prior notice to the User. Continued use of the website
                after changes are made indicates the User&apos;s agreement with
                the new terms.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
